<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Pomelo.EntityFrameworkCore.MySql"/>
	  <PackageReference Include="DotNetCore.CAP.MySql"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NXAI.Infra.Repository.EfCore\NXAI.Infra.Repository.EfCore.csproj" />
    <ProjectReference Include="..\NXAI.Infra.Repository\NXAI.Infra.Repository.csproj" />
  </ItemGroup>

</Project>
