<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MQTTnet" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\NXAI.Shared.Application\NXAI.Shared.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\NXAI.Shared.Pot\NXAI.Shared.Pot.csproj" />
    <ProjectReference Include="..\..\NXAI.Asset\NXAI.Asset.Application.Contracts\NXAI.Asset.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\NXAI.Member\NXAI.Member.Application.Contracts\NXAI.Member.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\NXAI.Inventory\NXAI.Inventory.Application.Contracts\NXAI.Inventory.Application.Contracts.csproj" />
    <ProjectReference Include="..\NXAI.Device.Application.Contracts\NXAI.Device.Application.Contracts.csproj" />
    <ProjectReference Include="..\NXAI.Device.Repository\NXAI.Device.Repository.csproj" />
  </ItemGroup>
</Project>
