<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\NXAI.Shared.Application\NXAI.Shared.Application.csproj" />
    <ProjectReference Include="..\NXAI.Device.Application.Contracts\NXAI.Device.Application.Contracts.csproj" />
    <ProjectReference Include="..\NXAI.Device.Repository\NXAI.Device.Repository.csproj" />
  </ItemGroup>
</Project>
