<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Castle.Core.AsyncInterceptor"  />
    <PackageReference Include="Polly" />
    <PackageReference Include="SkyAPM.Abstractions"  />
    <PackageReference Include="SkyAPM.Core"  />
    <PackageReference Include="SkyAPM.Utilities.DependencyInjection"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NXAI.Infra.Core\NXAI.Infra.Core.csproj" />
    <ProjectReference Include="..\NXAI.Infra.Redis\NXAI.Infra.Redis.csproj" />
  </ItemGroup>

</Project>
