<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Registrar\AbstractApplicationDependencyRegistrar.RpcClient.cs" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Http.Polly" />
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
	  <PackageReference Include="DotNetCore.CAP.RabbitMQ" />
	  <PackageReference Include="DotNetCore.CAP.MySql" />
	  <PackageReference Include="EFCore.NamingConventions" />
	  <PackageReference Include="AutoMapper" />
	  <PackageReference Include="FluentValidation" />
	  <PackageReference Include="Refit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructures\NXAI.Infra.EventBus\NXAI.Infra.EventBus.csproj" />
    <ProjectReference Include="..\..\Infrastructures\NXAI.Infra.IdGenerater\NXAI.Infra.IdGenerater.csproj" />
    <ProjectReference Include="..\..\Infrastructures\NXAI.Infra.Redis.Caching\NXAI.Infra.Redis.Caching.csproj" />
    <ProjectReference Include="..\..\Infrastructures\NXAI.Infra.Repository.Dapper\NXAI.Infra.Repository.Dapper.csproj" />
    <ProjectReference Include="..\..\Infrastructures\NXAI.Infra.Repository.EfCore.MySql\NXAI.Infra.Repository.EfCore.MySql.csproj" />
    <ProjectReference Include="..\NXAI.Shared.Application.Contracts\NXAI.Shared.Application.Contracts.csproj" />
    <ProjectReference Include="..\NXAI.Shared.Remote\NXAI.Shared.Remote.csproj" />
    <ProjectReference Include="..\NXAI.Shared.Repository\NXAI.Shared.Repository.csproj" />
    <ProjectReference Include="..\NXAI.Shared\NXAI.Shared.csproj" />
  </ItemGroup>

</Project>
