<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Yitter.IdGenerator"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NXAI.Infra.Redis\NXAI.Infra.Redis.csproj" />
  </ItemGroup>

</Project>
