<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DotNetCore.CAP" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\NXAI.Shared.Application\NXAI.Shared.Application.csproj" />
    <ProjectReference Include="..\..\NXAI.Cooking\NXAI.Cooking.Application.Contracts\NXAI.Cooking.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\NXAI.Device\NXAI.Device.Application.Contracts\NXAI.Device.Application.Contracts.csproj" />
    <ProjectReference Include="..\NXAI.Inventory.Application.Contracts\NXAI.Inventory.Application.Contracts.csproj" />
    <ProjectReference Include="..\NXAI.Inventory.Repository\NXAI.Inventory.Repository.csproj" />
  </ItemGroup>
</Project>
