<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\..\Shared\NXAI.Shared.WebApi\NXAI.Shared.WebApi.csproj" />
    <ProjectReference Include="..\NXAI.Cooking.Application.Contracts\NXAI.Cooking.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
